app:
  bind: 127.0.0.1
  port: 8093
  api_key: mysecretkey
  page_name: POGO Awesome
  page_img:
  page_img_width: 180
  page_img_height: 180
  auto_refresh: 30

timeout:
  green: 100
  yellow: 300
  red: 500

# Pages configuration
pages:
  show_services_table: true
  public_enabled: true  # enable public view
  public_show_devices: true  # show Device Name column on public view
  public_show_instances: true  # show Device Name column on public view
  public_show_interaction: true  # show Last Interaction column on public view
  hidden_enabled: true  # same as above but "hidden" view
  hidden_name: pikachu  # can't be none! to disable use `hidden_enabled` it's https://example.com/THISPART
  show_legend: true

# Used to hide devices/instances starting with names provided in list from public view
ignore:
  hidden_device_pattern:
    - test
  hidden_instance_pattern:
    - test_instance

# Replace X to Y in device/instance names. Order matter.
device_name_overwrite:
  - ["dev", "Scanner #"]

always_ok_status:

instance_name_overwrite:

rdm_database:
  enabled: true  # false not supported yet :D
  host: 127.0.0.1
  user: device_status
  password: mysecretpassword
  name: rdm
  connect_timeout: 5

lorg_database:
  enabled: false
  host: 127.0.0.1
  user: xxxx
  password: xxxx
  name: xxxx
  connect_timeout: 5

dcm_database:
  host: 127.0.0.1
  user: device_status
  password: mysecretpassword
  name: dcm
  connect_timeout: 5
